- name: get instack vm ip address
  register: instack_vm_ip_result
  shell: "cd {{ instack_user_home.stdout }}; cat /var/lib/libvirt/dnsmasq/default.leases | grep $(tripleo get-vm-mac instack) | awk '{print $3;}'"
  sudo_user: "{{ instack_user }}"
  sudo: yes